# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define() do

  create_table "activos", :force => true do |t|
    t.column "tipo_Activos_id", :integer,                              :null => false
    t.column "grupo_id",        :integer,                              :null => false
    t.column "serial",          :string,  :limit => 40,                :null => false
    t.column "modelo",          :string,  :limit => 40,                :null => false
    t.column "lock_version",    :integer,               :default => 0, :null => false
  end

  add_index "activos", ["id"], :name => "id", :unique => true

  create_table "bugs", :force => true do |t|
    t.column "reportedby",  :string
    t.column "assignedto",  :string
    t.column "description", :text
    t.column "status",      :string
    t.column "priority",    :string
  end

  create_table "cabequipos", :force => true do |t|
    t.column "nombre",  :string,                 :null => false
    t.column "config1", :string
    t.column "config2", :string, :default => ""
    t.column "config3", :string, :default => ""
    t.column "config4", :string, :default => ""
    t.column "config5", :string, :default => ""
  end

  create_table "cabpasajeros", :force => true do |t|
    t.column "cedula",       :string,                                 :null => false
    t.column "nacionalidad", :string,                                 :null => false
    t.column "nombres",      :string,                                 :null => false
    t.column "apellidos",    :string,                                 :null => false
    t.column "comentarios",  :text
    t.column "equipajes",    :text
    t.column "tipopasajero", :string,  :limit => 11,                  :null => false
    t.column "especial",     :string,  :limit => 11, :default => "0", :null => false
    t.column "cabvuelo_id",  :integer,                                :null => false
    t.column "puesto",       :string
    t.column "posicion",     :integer
    t.column "serie",        :integer
  end

  create_table "cabvuelos", :force => true do |t|
    t.column "nombrevuelo",  :string,                               :null => false
    t.column "fecha",        :string,                               :null => false
    t.column "hora",         :integer,                              :null => false
    t.column "minutos",      :integer,                              :null => false
    t.column "cabequipo_id", :integer,                              :null => false
    t.column "origen",       :string
    t.column "destino",      :string
    t.column "puerta",       :string
    t.column "conf01",       :string
    t.column "conf02",       :string
    t.column "conf03",       :string
    t.column "conf04",       :string
    t.column "conf05",       :string
    t.column "correlativo",  :integer, :limit => 10, :default => 0, :null => false
  end

  create_table "cargos", :force => true do |t|
    t.column "nombre_cargo", :string,  :limit => 60
    t.column "status",       :integer
    t.column "supervisor",   :integer
    t.column "lock_version", :integer,               :default => 0, :null => false
  end

  create_table "consumibles", :force => true do |t|
    t.column "nombre",       :string,  :limit => 50,                :null => false
    t.column "maximo",       :integer,                              :null => false
    t.column "minimo",       :integer,                              :null => false
    t.column "cantidad",     :integer,                              :null => false
    t.column "lock_version", :integer,               :default => 0, :null => false
  end

  add_index "consumibles", ["id"], :name => "id", :unique => true

  create_table "definecampos", :force => true do |t|
    t.column "defineproceso_id", :integer,                              :null => false
    t.column "tipocampo_id",     :integer,                              :null => false
    t.column "nombrecampo",      :string,  :limit => 40,                :null => false
    t.column "lock_version",     :integer,               :default => 0, :null => false
  end

  create_table "definelistacampos", :force => true do |t|
    t.column "definecampo_id", :integer,                              :null => false
    t.column "texto",          :string,  :limit => 40,                :null => false
    t.column "lock_version",   :integer,               :default => 0, :null => false
  end

  create_table "defineprocesos", :force => true do |t|
    t.column "total_pasos",    :integer,                              :null => false
    t.column "titulo_proceso", :string,  :limit => 60,                :null => false
    t.column "notas_proceso",  :text
    t.column "lock_version",   :integer,               :default => 0, :null => false
  end

  create_table "defineprocesos_usuarios", :id => false, :force => true do |t|
    t.column "usuario_id",       :integer
    t.column "defineproceso_id", :integer
  end

  create_table "equipos", :force => true do |t|
    t.column "tipo_equipo_id", :integer,                                :null => false
    t.column "grupo_id",       :integer,                                :null => false
    t.column "proveedor_id",   :integer,                                :null => false
    t.column "serial",         :string,  :limit => 40,                  :null => false
    t.column "modelo",         :string,  :limit => 40,                  :null => false
    t.column "garantia",       :integer,               :default => 0
    t.column "numero_factura", :string,  :limit => 40, :default => "0", :null => false
    t.column "lock_version",   :integer,               :default => 0,   :null => false
  end

  add_index "equipos", ["id"], :name => "id", :unique => true

  create_table "formularios", :force => true do |t|
    t.column "proceso_id",          :integer,                               :null => false
    t.column "definecampo_id",      :integer,                               :null => false
    t.column "nombre_campo",        :string,   :limit => 40,                :null => false
    t.column "fecha",               :datetime
    t.column "string",              :string,   :limit => 40
    t.column "texto",               :text
    t.column "definelistacampo_id", :integer
    t.column "lock_version",        :integer,                :default => 0, :null => false
  end

  create_table "gerencias", :force => true do |t|
    t.column "nombre_Gerencia",      :string,  :limit => 40,                :null => false
    t.column "responsable_Gerencia", :string,  :limit => 40
    t.column "telefono_Responsable", :string,  :limit => 20
    t.column "celular_Responsable",  :string,  :limit => 20
    t.column "lock_version",         :integer,               :default => 0, :null => false
  end

  add_index "gerencias", ["id"], :name => "id", :unique => true
  add_index "gerencias", ["nombre_Gerencia"], :name => "nombre_Gerencia", :unique => true

  create_table "grupos", :force => true do |t|
    t.column "nombre_Grupo", :string,  :limit => 40,                :null => false
    t.column "oficina_id",   :integer,                              :null => false
    t.column "gerencia_id",  :integer,                              :null => false
    t.column "usuario_id",   :integer
    t.column "lock_version", :integer,               :default => 0, :null => false
  end

  add_index "grupos", ["id"], :name => "id", :unique => true
  add_index "grupos", ["nombre_Grupo"], :name => "nombre_Grupo", :unique => true

  create_table "histforms", :force => true do |t|
    t.column "historicoproceso_id", :integer
    t.column "nombrecampo",         :string,  :limit => 40
    t.column "valorcampo",          :string,  :limit => 40
    t.column "lock_version",        :integer,               :default => 0, :null => false
  end

  create_table "histmsjprocs", :force => true do |t|
    t.column "historicoproceso_id", :integer
    t.column "titulo",              :string,   :limit => 40
    t.column "respuesta",           :text
    t.column "fecha",               :datetime
    t.column "status",              :string,   :limit => 40
    t.column "lock_version",        :integer,                :default => 0, :null => false
  end

  create_table "historico_activos", :force => true do |t|
    t.column "activos_id",      :integer,                               :null => false
    t.column "fecha",           :datetime,                              :null => false
    t.column "tipo_movimiento", :string,   :limit => 20,                :null => false
    t.column "origen_id",       :integer,                               :null => false
    t.column "destino_id",      :integer,                               :null => false
    t.column "motivo",          :text,                                  :null => false
    t.column "usuario_id",      :integer,                               :null => false
    t.column "lock_version",    :integer,                :default => 0, :null => false
  end

  add_index "historico_activos", ["id"], :name => "id", :unique => true

  create_table "historico_consumibles", :force => true do |t|
    t.column "consumibles_id",     :integer,                 :null => false
    t.column "fecha",              :datetime,                :null => false
    t.column "tipo_movimiento_id", :integer,                 :null => false
    t.column "origen_id",          :integer,                 :null => false
    t.column "destino_id",         :integer,                 :null => false
    t.column "motivo",             :text,                    :null => false
    t.column "usuario_id",         :integer,                 :null => false
    t.column "cantidad",           :integer,                 :null => false
    t.column "lock_version",       :integer,  :default => 0, :null => false
  end

  add_index "historico_consumibles", ["id"], :name => "id", :unique => true

  create_table "historico_equipos", :force => true do |t|
    t.column "equipo_id",          :integer,                  :null => false
    t.column "fecha",              :timestamp,                :null => false
    t.column "tipo_movimiento_id", :integer,                  :null => false
    t.column "Origen_id",          :integer,                  :null => false
    t.column "Destino_id",         :integer,                  :null => false
    t.column "Motivo",             :text,                     :null => false
    t.column "usuario_id",         :integer,                  :null => false
    t.column "lock_version",       :integer,   :default => 0, :null => false
  end

  add_index "historico_equipos", ["id"], :name => "id", :unique => true

  create_table "historico_mensajes", :force => true do |t|
    t.column "origen_id",         :integer,                               :null => false
    t.column "usuario_id",        :integer,                               :null => false
    t.column "titulo",            :string,   :limit => 40,                :null => false
    t.column "txt_origen",        :text
    t.column "txt_hold",          :text
    t.column "txt_respuesta",     :text
    t.column "status",            :integer,                :default => 0, :null => false
    t.column "fecha_emision",     :datetime
    t.column "fecha_inicio_hold", :datetime
    t.column "fecha_respuesta",   :datetime
    t.column "lock_version",      :integer,                :default => 0, :null => false
  end

  create_table "historicoprocesos", :force => true do |t|
    t.column "proceso_id",   :integer
    t.column "login",        :string,   :limit => 40
    t.column "titulo",       :string,   :limit => 40
    t.column "texto",        :text
    t.column "status",       :string,   :limit => 40
    t.column "fecha",        :datetime
    t.column "lock_version", :integer,                :default => 0, :null => false
  end

  create_table "mensajes", :force => true do |t|
    t.column "origen_id",         :integer,                               :null => false
    t.column "usuario_id",        :integer,                               :null => false
    t.column "titulo",            :string,   :limit => 40,                :null => false
    t.column "txt_origen",        :text
    t.column "txt_hold",          :text
    t.column "txt_respuesta",     :text
    t.column "status",            :integer,                :default => 0, :null => false
    t.column "fecha_emision",     :datetime
    t.column "fecha_inicio_hold", :datetime
    t.column "fecha_respuesta",   :datetime
    t.column "lock_version",      :integer,                :default => 0, :null => false
  end

  create_table "modulos", :force => true do |t|
    t.column "nombre_modulo", :string,  :limit => 40,                :null => false
    t.column "lock_version",  :integer,               :default => 0, :null => false
  end

  create_table "modulos_usuarios", :id => false, :force => true do |t|
    t.column "usuario_id", :integer, :null => false
    t.column "modulo_id",  :integer, :null => false
  end

  create_table "msj_defineprocesos", :force => true do |t|
    t.column "defineproceso_id", :integer,                              :null => false
    t.column "nro_paso",         :integer
    t.column "usuario_id",       :integer,                              :null => false
    t.column "titulo",           :string,  :limit => 40,                :null => false
    t.column "txt_mensaje",      :text
    t.column "lock_version",     :integer,               :default => 0, :null => false
  end

  create_table "msj_procesos", :force => true do |t|
    t.column "proceso_id",           :integer,                 :null => false
    t.column "msj_defineproceso_id", :integer
    t.column "txt_origen",           :text
    t.column "txt_respuesta",        :text
    t.column "txt_hold",             :text
    t.column "status",               :integer
    t.column "fecha_emision",        :datetime
    t.column "fecha_inicio_hold",    :datetime
    t.column "fecha_respuesta",      :datetime
    t.column "nombre_archivo",       :string
    t.column "tipo_archivo",         :string
    t.column "size_archivo",         :string
    t.column "archivo",              :binary
    t.column "lock_version",         :integer,  :default => 0, :null => false
  end

  create_table "noticias", :force => true do |t|
    t.column "fecha",        :timestamp,                              :null => false
    t.column "titulo",       :string,    :limit => 40,                :null => false
    t.column "mensaje",      :text,                                   :null => false
    t.column "lock_version", :integer,                 :default => 0, :null => false
  end

  create_table "oficinas", :force => true do |t|
    t.column "nombre_Oficina",    :string,  :limit => 40,                :null => false
    t.column "ubicacion_Oficina", :text
    t.column "telefono_Oficina",  :string,  :limit => 20
    t.column "fax_Oficina",       :string,  :limit => 20
    t.column "sucur_id",          :integer,                              :null => false
    t.column "lock_version",      :integer,               :default => 0, :null => false
  end

  add_index "oficinas", ["id"], :name => "id", :unique => true
  add_index "oficinas", ["nombre_Oficina"], :name => "nombre_Oficina", :unique => true

  create_table "procesos", :force => true do |t|
    t.column "usuario_id",       :integer,                 :null => false
    t.column "defineproceso_id", :integer,                 :null => false
    t.column "txt_proceso",      :text,                    :null => false
    t.column "status",           :integer,                 :null => false
    t.column "paso_actual",      :integer,                 :null => false
    t.column "fecha",            :datetime,                :null => false
    t.column "lock_version",     :integer,  :default => 0, :null => false
  end

  create_table "proveedors", :force => true do |t|
    t.column "nombre_proveedor",    :string,  :limit => 40,                :null => false
    t.column "direccion_proveedor", :text
    t.column "telefono1_proveedor", :string,  :limit => 20
    t.column "telefono2_proveedor", :string,  :limit => 20
    t.column "telefono3_proveedor", :string,  :limit => 20
    t.column "celular_proveedor",   :string,  :limit => 20
    t.column "fax_proveedor",       :string,  :limit => 20
    t.column "lock_version",        :integer,               :default => 0, :null => false
  end

  add_index "proveedors", ["id"], :name => "id", :unique => true
  add_index "proveedors", ["nombre_proveedor"], :name => "nombre_proveedor", :unique => true

  create_table "sucurs", :force => true do |t|
    t.column "nombre_Sucursal",    :string,  :limit => 40,                :null => false
    t.column "direccion_Sucursal", :text,                                 :null => false
    t.column "telefono_Sucursal",  :string,  :limit => 20
    t.column "fax_Sucursal",       :string,  :limit => 20
    t.column "lock_version",       :integer,               :default => 0, :null => false
  end

  add_index "sucurs", ["id"], :name => "id", :unique => true
  add_index "sucurs", ["nombre_Sucursal"], :name => "nombre_Sucursal", :unique => true

  create_table "tipo_activos", :force => true do |t|
    t.column "nombre_activo", :string,  :limit => 40,                :null => false
    t.column "lock_version",  :integer,               :default => 0, :null => false
  end

  add_index "tipo_activos", ["id"], :name => "id", :unique => true

  create_table "tipo_consumibles", :force => true do |t|
    t.column "nombre_consumible", :string,  :limit => 40,                :null => false
    t.column "lock_version",      :integer,               :default => 0, :null => false
  end

  add_index "tipo_consumibles", ["id"], :name => "id"

  create_table "tipo_equipos", :force => true do |t|
    t.column "nombre_equipo", :string,  :limit => 40,                :null => false
    t.column "lock_version",  :integer,               :default => 0, :null => false
  end

  add_index "tipo_equipos", ["id"], :name => "id", :unique => true
  add_index "tipo_equipos", ["nombre_equipo"], :name => "nombre_equipo", :unique => true

  create_table "tipocampos", :force => true do |t|
    t.column "tipo",         :string,  :limit => 40,                :null => false
    t.column "lock_version", :integer,               :default => 0, :null => false
  end

  create_table "usuarios", :force => true do |t|
    t.column "nombres",         :string,   :limit => 50,                :null => false
    t.column "apellidos",       :string,   :limit => 50,                :null => false
    t.column "fechanac",        :datetime
    t.column "cedula",          :string,   :limit => 40,                :null => false
    t.column "login",           :string,   :limit => 40,                :null => false
    t.column "hashed_password", :string,   :limit => 40,                :null => false
    t.column "controlador",     :string,   :limit => 40
    t.column "accion",          :string,   :limit => 40
    t.column "cargo_id",        :integer
    t.column "gerencia_id",     :integer,                               :null => false
    t.column "oficina_id",      :integer,                               :null => false
    t.column "lock_version",    :integer,                :default => 0, :null => false
  end

  add_index "usuarios", ["id"], :name => "id", :unique => true
  add_index "usuarios", ["login"], :name => "login", :unique => true

end
